### PR TITLE
Maven

### PR DESCRIPTION
**Pull request by dblaisdell**
Converted the build to use maven. 
* Replaced versions in 3rd party library with maven dependencies
* WSDL2Java with Axis 1.4 drops .java into generated sources

### CODE REVIEW

**Comment by joepruitt** [comment]
I'm working on the BIG-IP v13.0.0 version for this library and am giving the maven version a go but do not see everything compiled and packaged up.  Specifically src/main/java/iControl/Interfaces.java and XTrustProvider.java are not included in the build and a resulting iControl.jar isn't generated.  Is this meant to just compile the .wsdl files?  That it seems to do fine, just am not getting the other source files included and packaging.  Is this by design?

**Comment by dblaisdell** [comment]
That is not by design, let me run some more tests and ill let you know.

**Comment by dblaisdell** [comment]
Thanks for reviewing, everything should compile cleanly now.

Had to fix the case of generated classes in Interfaces to get it to compile.

**Comment by joepruitt** [comment]
I went ahead and merged the pull request but there is still one outstanding issue.  The naming of the classes with lower case letters are getting converted to upper case (ie. iCall* -> ICall*).  I see you hard coded a fix in the Interfaces.cs but that breaks breaks backward compatibility for existing clients using this library.  I have a PowerShell script (now in legacy\FixCaseInBindings.ps1) that needs to get run after the WSDL compile into .java and before the java compile into .class.  Something like this:

.\legacy\FixCaseInBindings.ps1 .\src\main\resources\wsdl .\src\generated\java\iControl

How easy is it to add this custom command after the wsdl2java and before the javac?

**Comment by joepruitt** [comment]
Ideally I'll want a cross platform way to do this so maybe I'll rewrite it in Perl but for the mean time it's in PowerShell (windows).  Haven't tested if that will work on a unix build of PowerShell but it likely should.

**Comment by dblaisdell** [comment]
Java is pretty specific about how classes should be named. Let me take a look at what the powershell script is doing. You should make a separate issue for this effort.

**Pull request merged**
